//! Auto-generated `bindings.rs` codegen for Malphas v2.7.5 systems.
//!
//! The compiler writes an immutable Rust module containing every Entity ID and
//! Tag mask declared in the workspace manifest.  Systems include this file so
//! the compiler can inline the constants at `-O3`.

use std::error::Error;
use std::fs;
use std::io::Write;
use std::path::Path;

use crate::manifest::Manifest;

/// Sanitize a string into a valid Rust identifier segment.
fn sanitize(name: &str) -> String {
    let mut out = String::with_capacity(name.len());
    for c in name.chars() {
        if c.is_ascii_alphanumeric() {
            out.push(c.to_ascii_uppercase());
        } else {
            out.push('_');
        }
    }
    if out.is_empty() || out.starts_with(|c: char| c.is_ascii_digit()) {
        out.insert(0, '_');
    }
    out
}

/// Generate a `bindings.rs` file from the manifest.
pub fn generate_bindings(manifest: &Manifest, output_path: &Path) -> Result<(), Box<dyn Error>> {
    let mut content = String::new();
    content.push_str("// Auto-generated by malphas-cli. Do not edit by hand.\n");
    content.push_str("// Generated from manifest: ");
    content.push_str(&manifest.pack_id);
    content.push('\n');
    content.push('\n');

    content.push_str(&format!(
        "pub const PACK_ID: &str = \"{}\";\n",
        manifest.pack_id
    ));
    content.push_str(&format!(
        "pub const ENTITY_COUNT: u32 = {};\n\n",
        manifest.entities.len()
    ));

    for entity in &manifest.entities {
        let name = sanitize(&format!("ENTITY_{}", entity.entity_id));
        content.push_str(&format!(
            "pub const {}: u32 = {};\n",
            name, entity.entity_id
        ));

        let tag_name = sanitize(&format!("TAG_MASK_{}", entity.entity_id));
        content.push_str(&format!(
            "pub const {}: u64 = {};\n",
            tag_name, entity.tag_mask
        ));
        content.push('\n');
    }

    let mut file = fs::File::create(output_path)?;
    file.write_all(content.as_bytes())?;
    file.flush()?;
    Ok(())
}

/// Generate bindings next to the manifest file.
pub fn generate_bindings_next_to_manifest(
    manifest: &Manifest,
    manifest_dir: &Path,
) -> Result<(), Box<dyn Error>> {
    let output_path = manifest_dir.join("bindings.rs");
    generate_bindings(manifest, &output_path)?;
    println!("Generated: {}", output_path.display());
    Ok(())
}

#[cfg(test)]
mod tests {
    use super::*;
    use std::path::PathBuf;

    #[test]
    fn generate_bindings_writes_constants() {
        let tmp_dir =
            std::env::temp_dir().join(format!("malphas_bindings_test_{}", std::process::id()));
        fs::create_dir_all(&tmp_dir).unwrap();

        let manifest = Manifest {
            pack_id: "demo_pack".to_string(),
            entities: vec![
                crate::manifest::ManifestEntity {
                    entity_id: 0,
                    tag_mask: 1,
                    payload_file: PathBuf::from("a.bin"),
                },
                crate::manifest::ManifestEntity {
                    entity_id: 42,
                    tag_mask: 0xFF,
                    payload_file: PathBuf::from("b.bin"),
                },
            ],
        };

        let output = tmp_dir.join("bindings.rs");
        generate_bindings(&manifest, &output).unwrap();

        let text = fs::read_to_string(&output).unwrap();
        assert!(text.contains("pub const ENTITY_0: u32 = 0;"));
        assert!(text.contains("pub const TAG_MASK_0: u64 = 1;"));
        assert!(text.contains("pub const ENTITY_42: u32 = 42;"));
        assert!(text.contains("pub const TAG_MASK_42: u64 = 255;"));
        assert!(text.contains("pub const ENTITY_COUNT: u32 = 2;"));

        let _ = fs::remove_file(&output);
        let _ = fs::remove_dir(&tmp_dir);
    }

    #[test]
    fn sanitize_makes_valid_identifiers() {
        assert_eq!(sanitize("entity-1"), "ENTITY_1");
        assert_eq!(sanitize("1st"), "_1ST");
        assert_eq!(sanitize(""), "_");
    }
}
